version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    hostname: redis.local
    ports:
      - "127.0.0.1:6379:6379"
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=transfer"
    volumes:
      - ./www/data/mysql:/var/lib/mysql
    ports:
    - "3306:3306"
  php:
    container_name: php
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
networks:
  default:
    external:
      name: root_default